import type { IconType } from '../../types/icon';

export const getIconFilePath = (type: IconType) => {
  switch (type) {
    case 'add':
      return '../../assets/icons/add.svg';
    case 'arrow-left':
      return '../../assets/icons/arrow_left.svg';
    case 'arrow-next':
      return '../../assets/icons/arrow_next.svg';
    case 'arrow-previous':
      return '../../assets/icons/arrow_previous.svg';
    case 'arrow-right':
      return '../../assets/icons/arrow_right.svg';
    case 'bag':
      return '../../assets/icons/bag.svg';
    case 'bag-add':
      return '../../assets/icons/bag_add.svg';
    case 'bag-added':
      return '../../assets/icons/bag_added.svg';
    case 'bag-checked':
      return '../../assets/icons/bag_checked.svg';
    case 'bell':
      return '../../assets/icons/bell.svg';
    case 'calendar':
      return '../../assets/icons/calendar.svg';
    case 'cart':
      return '../../assets/icons/cart.svg';
    case 'caution':
      return '../../assets/icons/caution.svg';
    case 'cellphone':
      return '../../assets/icons/cellphone.svg';
    case 'chat-bubble':
      return '../../assets/icons/chat_bubble.svg';
    case 'check':
      return '../../assets/icons/check.svg';
    case 'chevron-down':
      return '../../assets/icons/chevron_down.svg';
    case 'chevron-up':
      return '../../assets/icons/chevron_up.svg';
    case 'clipboard':
      return '../../assets/icons/clipboard.svg';
    case 'conversation':
      return '../../assets/icons/conversation.svg';
    case 'coupon':
      return '../../assets/icons/coupon.svg';
    case 'credit-card':
      return '../../assets/icons/credit_card.svg';
    case 'dog':
      return '../../assets/icons/dog.svg';
    case 'dog-house':
      return '../../assets/icons/dog_house.svg';
    case 'dog-walker':
      return '../../assets/icons/dog_walker.svg';
    case 'eye-closed':
      return '../../assets/icons/eye_closed.svg';
    case 'eye-open':
      return '../../assets/icons/eye_open.svg';
    case 'filter':
      return '../../assets/icons/filter.svg';
    case 'headset':
      return '../../assets/icons/headset.svg';
    case 'image':
      return '../../assets/icons/image.svg';
    case 'letter-closed':
      return '../../assets/icons/letter_close.svg';
    case 'letter-open':
      return '../../assets/icons/letter_open.svg';
    case 'list':
      return '../../assets/icons/list.svg';
    case 'list-details':
      return '../../assets/icons/list_details.svg';
    case 'location':
      return '../../assets/icons/location.svg';
    case 'lock':
      return '../../assets/icons/lock.svg';
    case 'login':
      return '../../assets/icons/login.svg';
    case 'logout':
      return '../../assets/icons/logout.svg';
    case 'magnifier':
      return '../../assets/icons/magnifier.svg';
    case 'menu':
      return '../../assets/icons/menu.svg';
    case 'message':
      return '../../assets/icons/message.svg';
    case 'money-transference':
      return '../../assets/icons/money_transference.svg';
    case 'order':
      return '../../assets/icons/order.svg';
    case 'pencil':
      return '../../assets/icons/pencil.svg';
    case 'pet-grooming':
      return '../../assets/icons/pet_grooming.svg';
    case 'pet-health':
      return '../../assets/icons/pet_health.svg';
    case 'question':
      return '../../assets/icons/question.svg';
    case 'reload':
      return '../../assets/icons/reload.svg';
    case 'repeat':
      return '../../assets/icons/repeat.svg';
    case 'save':
      return '../../assets/icons/save.svg';
    case 'search':
      return '../../assets/icons/search.svg';
    case 'send':
      return '../../assets/icons/send.svg';
    case 'shower':
      return '../../assets/icons/shower.svg';
    case 'star':
      return '../../assets/icons/star.svg';
    case 'star-badge':
      return '../../assets/icons/star_badge.svg';
    case 'stars':
      return '../../assets/icons/stars.svg';
    case 'text':
      return '../../assets/icons/text.svg';
    case 'text-bubble':
      return '../../assets/icons/text_bubble.svg';
    case 'trash':
      return '../../assets/icons/trash.svg';
    case 'truck':
      return '../../assets/icons/truck.svg';
    case 'user':
      return '../../assets/icons/user.svg';
    case 'wallet':
      return '../../assets/icons/wallet.svg';
    default:
      return '';
  }
};
